### ISSUE TITLE
Přidat drobet umělou inteligenci

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#10]
Nepřítel by měl, pokud má možnost zničit hrdinu ne pouze náhodně zkoušet věci :)

**Comment by fan1x** [comment]
Zkus použít nějaké známe algoritmy případně vymyslet vlastní algoritmus na to....

**Comment by KatDan** [comment]
nová stratégia nepriateľa je takáto: 
- keď má viac života ako hrdina, útočí na hrdinu.
- keď má menej života, ale vedel by hrdinu zabiť na 2 seky silou posledného vykonaného útoku, útočí (sila útoku sa stále generuje náhodne v rozmedzí 50%-150% sily atribútu útok, takže niekedy nepriateľ môže prestreliť a seknúť slabšie ako chcel, ale potom sa tá podmienka sily 2 sekov updatne a nepriateľ znovu zváži útek)
- ak nepriateľ neútočí, je v nevýhode. Preto cúva, kým sa dá, a keď sa už nedá, tak z posledných síl útočí a uvidí, čo to dá, po chvíli bude buď vo výhode alebo zahynie krutou smrťou.

**Comment by fan1x** [comment]
Napsat to do dokumentace. 
Jinka, ještě bych to zkusil vylepšit. Stalo se mi, že nepřítel couval, tak jsem k němu šel a on pak zaútočil a zabil mě na první ránu 🤣 
Zkusil bych ještě změnit nějak to couvání. Jelikož chudák nemá moc kam utéct, tak to nedává nutně vždy smysl. Jinak, mají nepřátelé také lektvary? Bylo by to super :)

**Comment by fan1x** [comment]
> Napsat to do dokumentace.
prehledl jsem....
