### ISSUE TITLE
Konzistentní pojmenování

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#11]
Občas s velkými, občas s malými. Vybrat si jeden styl a ten dodržovat po celý kód. C# má nějaký doporučený styl, který je jiný než používáš (to nevadí, ale je důležité ho všude používat důsledně)

**Comment by fan1x** [comment]
Např: 
https://github.com/KatDan/WarriorsOfTheBlackField/blob/f27bba46e73a72260a1b6032c4674bbca5aeea01/WarriorsOfTheBlackFieldForest/WarriorsOfTheBlackFieldForest/Postava.cs#L121

https://github.com/KatDan/WarriorsOfTheBlackField/blob/f27bba46e73a72260a1b6032c4674bbca5aeea01/WarriorsOfTheBlackFieldForest/WarriorsOfTheBlackFieldForest/Postava.cs#L295

**Comment by fan1x** [comment]
Také si vybrat jeden jazyk a ten používat, občas používáš češtinu, občas angličtinu...

**Comment by KatDan** [comment]
funkcie sú zmalopísmenkované, premenovala som veci, aby boli po československy (slovo "padouch" musím nechať, po slovensky to vôbec neznie dobre)

**Comment by fan1x** [comment]
Jak se to řekne slovensky?  Gauner? 😄

**Comment by KatDan** [comment]
gauner, zlosyn, zloduch... nič z toho neznie lepšie ako padouch :D
