### ISSUE TITLE
Hezčí návrh

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#12]
Proč to například v readonly poli? https://github.com/KatDan/WarriorsOfTheBlackField/blob/df9469d032d90c8ac0d444b243fd27d809c9cab7/WarriorsOfTheBlackFieldForest/WarriorsOfTheBlackFieldForest/Level.cs#L50

**Comment by KatDan** [comment]
case-y som nahradila poľom obrázkov, takže teraz sa generuje len náhodný index a vyberie sa príslušný obrázok (mal si na mysli takéto zhezčenie?).
