### ISSUE TITLE
Udělat "nekonečnou hru" (bonus)

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#14]
Stará RPG dřív dělala to (možná i ty dnešní, nevím...), že například v dungeonech generovali náhodně další a další kola a protivníky. Strašně by se mi líbilo, kdyby tohle fungovalo podobně. 
Je strašná škoda, že to po 5 levelec končí - udělal bych to nekonečné, nepřátelé by se náhodně vylepšovali podobně jako hrdina (možná lehce rychleji) a cílem by bylo se dostat co nejdál (do co nejvyššího levelu). Kdyby potom ještě šlo mít scoreboard (mít možnost se podepsat, když jsi mezi prvními 10 lidmi), tak je to úplně boží 🥇

**Comment by KatDan** [comment]
Želanie splnené, teraz je nekonečno levelov a nepriatelia sa vylepšujú podľa drsnejšieho vzorca, aby to bolo zaujímavejšie. Opravila som tým pádom aj How to play manuál a dokumentáciu. Dúfam, že je to bez chýb. Ak by si nejakú chybu našiel, tak commit s urobeným bonusom radšej revertnem a môžeme sa tváriť, že nikdy neexistoval :D (povinné issues boli vyriešené v predošlých commitoch)
