### ISSUE TITLE
GUI se občas rozpadně

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#3]
![error1](https://user-images.githubusercontent.com/2750870/62821430-0de21980-bb75-11e9-9b7e-a1df83bb2cae.png)

**Comment by KatDan** [comment]
ak som to správne pochopila, How to play má vedieť aj zmiznúť, potom je to opravené. Ak nie, poprosím podrobnejší opis problému.

**Comment by fan1x** [comment]
Spíš mi šlo o to, že když se otevře "How to play" tak zatím textboxem kouká tlačítko, což je ošklivé...

**Comment by fan1x** [comment]
Navíc nelze vypnout credits?
