### ISSUE TITLE
Špatně fungují stats

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#4]
Když hraji podruhé (poprvé jsem zemřel), tak to ukazuje, že mi HP zůstavají (při upgradu), ale při hře se zobrazí a po prvním kruku zmizí...

**Comment by fan1x** [comment]
Možná s tím souvisí i problém, že mi to potom, co jsem zemřel, dává na začátek strašně silné protivníky, které nemám moc šancí porazit

**Comment by fan1x** [comment]
Tohle není opravené... :( Když zemřu, tak ukazatel stále ukazuje HP10 ikdyž mám HP jiné

**Comment by KatDan** [comment]
už pri upgradeovaní po smrti ukáže HP po leveli 1 základných 10 bodov
