### ISSUE TITLE
Pojmenovat nějak rozumně

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#5]
https://github.com/KatDan/WarriorsOfTheBlackField/blob/e536fc3da74fe14e9c685d23116aeaffc9f7d7a1/WarriorsOfTheBlackFieldForest/WarriorsOfTheBlackFieldForest/Form1.cs#L13

**Comment by KatDan** [comment]
premenované na Hra.cs
