### ISSUE TITLE
Pospojovat spolecne veci do spolecne struktury/tridy

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#7]
Např:
```
internal Label stat1;
internal Label stat2;
internal Label stat3;
internal Label stat4;

->

struct Stats {
    Label[4] stats;
}
```

a podobně.

Obecně, když předáváš hodně parametrů funkci (https://github.com/KatDan/WarriorsOfTheBlackField/blob/e536fc3da74fe14e9c685d23116aeaffc9f7d7a1/WarriorsOfTheBlackFieldForest/WarriorsOfTheBlackFieldForest/Form1.cs#L726) může to být signál, že by mohli být společně někde v nějaké struktuře

**Comment by fan1x** [comment]
Podobně s:
```
internal Timer hrdina_timer_krok_vpred;
internal Timer hrdina_timer_krok_vzad;
internal Timer padouch_timer_krok_vpred;
internal Timer padouch_timer_krok_vzad;
```

Místo oddělování pomocí podtržítek, rozdělit to na struktury:
```
struct KrokTimers 
{
  Timer vpred;
  Timer vzad;
}

internal KrokTimers hrdina;
internal KrokTimers padouch
```

**Comment by KatDan** [comment]
snáď už to bude ok

**Comment by fan1x** [comment]
A co například: https://github.com/KatDan/WarriorsOfTheBlackField/blob/df9469d032d90c8ac0d444b243fd27d809c9cab7/WarriorsOfTheBlackFieldForest/WarriorsOfTheBlackFieldForest/Postava.cs#L31

Všimni si, že sama podvědomě víš, že věci patří k sobě (jmenují se box_*), tak místo toho, abys dávala stejné jméno, tak věci dávej do stejné třídy
