### ISSUE TITLE
Nahrát do GITu je soubory, které tam patří

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#8]
V GITu jsou nahrané i soubory, které sem nepatří. Zkus pogooglit (něco jako "GIT C#"), kde bys měla najít co patří do GITu a co ne. Obecně tam nepatří BINárky (EXE, ...) a uživatelské soubory. Měl by obsahovat minimum věcí, ale aby to šlo přeložit (ideální je to ozkoušet, vyclonovat si repo někde vedle)

**Comment by KatDan** [comment]
Zmazala som veci, ktoré tam podľa .gitignore listu nemajú byť, takže už by tam mali byť len potrebné veci (dúfam).
