### ISSUE TITLE
Program po chvíli hraní vyhodil exception

### ISSUE THREAD

**Issue by fan1x** [KatDan/WarriorsOfTheBlackField#9]
![error2](https://user-images.githubusercontent.com/2750870/63810628-76771780-c925-11e9-8e1a-7a2c2fb96929.png)

**Comment by fan1x** [comment]
Jiný problém a opět exception
![error2](https://user-images.githubusercontent.com/2750870/63811102-cdc9b780-c926-11e9-9b3e-169129c3c482.png)

**Comment by KatDan** [comment]
prvý problém opravený, druhý asi súvisí s hlúposťou padoucha, takže s novou AI by to už hádzať exception snáď nemalo
